#!/usr/bin/env php
<?php
/**
 * tpAdmin [a web admin based ThinkPHP5]
 *
 * @author yuan1994 <tianpian0805@gmail.com>
 * @link http://tpadmin.yuan1994.com/
 * @copyright 2016 yuan1994 all rights reserved.
 * @license http://www.apache.org/licenses/LICENSE-2.0
 */

// 定义项目路径
define('APP_PATH', __DIR__ . '/application/');

// 加载框架引导文件
require './extend/console/console.php';